### ISSUE TITLE
the demo video is private

### ISSUE THREAD

**Issue by user2589** [mcore1976/sim808gpstracker#1]
To reproduce, open in a private window:
https://www.youtube.com/watch?v=ZMRz5Emcvew

**Comment by mcore1976** [comment]
Thanks for letting me know. I had better video for current revision of the code which was showing how gpstracker is working now. In the video screen output it showed my exact location with 3 meter accuracy. I was unable to blur some fragments and I had to change it to private for security reasons. I have changed the link to previous video...
